- hosts: servers
  become: true
  tasks: 
  - name: installing apache2
    apt:
     name: apache2
     state: present

  - name: checking apache service
    service:
     name: apache2 
     state: started
     enabled: ye